package modelo;
// Generated 14 nov 2023 10:53:13 by Hibernate Tools 6.1.3.Final

import java.math.BigDecimal;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private Short codigo;
	private Departamento departamento;
	private String nombre;
	private String fechaAlta;
	private BigDecimal salario;

	public Empleado() {
	}

	public Empleado(Departamento departamento, String nombre, String fechaAlta, BigDecimal salario) {
		this.departamento = departamento;
		this.nombre = nombre;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
	}

	public Short getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Short codigo) {
		this.codigo = codigo;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(String fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public BigDecimal getSalario() {
		return this.salario;
	}

	public void setSalario(BigDecimal salario) {
		this.salario = salario;
	}

	@Override
	public String toString() {
		return 
			"Empleado [C�digo = " + codigo + 
			", Nombre = " + nombre + 
			", FechaAlta = " + fechaAlta + 
			", Salario = " + salario + 
			//",\n    Departamento = " + departamento.toString() +
			"]";
	}
	
}
